Cursor32
MFC42.DLL
MSVCRT.DLL
Windows
[BugFix]
[NEW]
[VerUp]
delete
inoue-h@iname.com
version
v‚ðŽw’è‚µ‚Ä‹N“®‚µ‚Ä‚­‚¾‚³‚¢B
‚ ‚Æ‚ª‚«A•ÏX—š—ð
‚¨‚æ‚Ñ
‚µA‘¼‚ÌƒvƒƒOƒ‰ƒ€‚Æ‚Ì‹£‡‚ð‚³‚¯‚é‚æ‚¤‚É‚µ‚Ä‚­‚¾‚³‚¢B
‚Å‚·B
‚Ìu•\Ž¦ŠÔŠuv‚Å‚P‚O‚Oƒ~ƒŠ•bˆÊ‚ª“K“–‚Å‚·B
‚Ìƒpƒ‰ƒ[ƒ^[‚Éu
‚ÌÄ‹N“®‚ª•K—v‚Å‚·B
ƒAƒ“ƒCƒ“ƒXƒg[ƒ‹
ƒCƒ“ƒXƒg[ƒ‹
ƒGƒ‰[‚Æ‘Îô
ƒ^ƒXƒNƒo[
ƒ_ƒCƒAƒƒO
ƒvƒƒ“ƒvƒg‚È‚Ç‚©‚çs‚¤‚±‚Æ‚ªo—ˆ‚Ü‚·B
ƒ}ƒEƒX
ƒ}ƒEƒXƒJ[ƒ\ƒ
ƒ}ƒEƒXƒJ[ƒ\ƒ‹EƒAƒVƒXƒ^ƒ“ƒX‹@”\
ƒƒOƒIƒ“Žž‚É
‹@”\Ý’è
À•W‚Ì•\Ž¦F‚ð•ÏX
Žg‚¤‚Ì‚ð‚â‚ß‚é
Žg—p‹–‘øðŒ
‰‚ß‚ÄŽg‚¤‚Æ‚«
§ŒÀŽ–€
’Êí‚Í
“ú–{Œê”ÅˆÈŠO‚Ì
•\Ž¦ŠÔŠu
